### ISSUE TITLE
cant compile IceFloeConsole 

### ISSUE THREAD

**Issue by urwiramboll** [NWTC/IceFloe#1]
I want to compile Iceflow as a console application according the screenshot for IceFloeConsole in 
* https://github.com/old-NWTC/IceFloe/blob/master/compiling/Notes%20on%20compiling%20IceFloe.pdf

I am missing two files:
* SingPrec.f90    (which I could find in https://github.com/old-NWTC/NWTC_Library/blob/master/source/SingPrec.f90)
* NWTC_IO_reduced.f90

Where can I get the missing sources or do I have forgotten something?

BR
Urs

**Comment by jjonkman** [comment]
Hi Urs -- I have no experience compiling the IceFloe console application myself, but I asked Bonnie and she said that you can probably compile IceFloe with the source files from NWTC library (instead of using NWTC_IO_reduced.f90 etc.).  Let me know if that works for you.  Best regards,

**Comment by urwiramboll** [comment]
Hi Jason,

thanks for you very much for the hint. I am now able to compile with the following modifications:
I used the following sources from /old-NWTC/NWTC_Library:
* NWTC_Library\source\NWTC_Base.f90
* NWTC_Library\source\NWTC_IO.f90
* NWTC_Library\source\NWTC_Library_Types.f90
* NWTC_Library\source\SingPrec.f90
* NWTC_Library\source\SysIVF.f90

Since the signature of ```NameOFile``` has changed, I had to change
```diff
diff --git a/source/interfaces/Console/IceFloe.f90 b/source/interfaces/Console/IceFloe.f90
index 6929fd6..aa1b0f4 100644
--- a/source/interfaces/Console/IceFloe.f90
+++ b/source/interfaces/Console/IceFloe.f90
@@ -62,6 +62,10 @@ program IceFloe
    character(132)             :: logFile  ! File name for message logging
    character(132)             :: inputFile
    character(132)             :: outFile
+
+   INTEGER                    :: errStat
+   character(132)             :: errMsg
+
    integer(IntKi)             :: outUnitNum, numArg, n, nL

 ! get parameter input file from command line
@@ -82,7 +86,7 @@ program IceFloe

    CALL DispNVD( IceFloe_Ver )

-   call NameOFile ( 1, 'log', logFile )   ! The filename comes from the command line
+   call NameOFile ( 1, 'log', logFile, ErrStat, ErrMsg )   ! The filename comes from the command line
    call openIceLog (theIceLog, logFile)
    call logMessage(theIceLog, ' Running: '//ProgName_ice//', '//ProgVer_ice//', '//Progdate_ice)
    call logMessage(theIceLog, ' This run started on: '//curdate()//' at '//curtime()//newLine)
@@ -171,7 +175,7 @@ program IceFloe
    if (theIceLog%ErrID >= AbortErrLev) stop

 !  Ouput time series of loads to ASCII file
-   call NameOFile ( 1, 'dat', outFile )   ! The filename comes from the command line
+   call NameOFile ( 1, 'dat', outFile, ErrStat, ErrMsg )   ! The filename comes from the command line
    call GetNewUnit ( outUnitNum, Err, Msg )
    if (Err >= ErrID_Severe) then
       call iceErrorHndlr (theIceLog, ErrID_Fatal, 'Error obtaining output file handle: '//newLine//trim(Msg), 1)
```

**Comment by jjonkman** [comment]
OK, great!  I'm you were able to solve the problem.
